name: build

on:
  push:
    branches:
      - master
    paths:
      - 'Device/**'
      - 'include/**'
      - 'ldscripts/**'
  pull_request:
    branches:
      - master
    paths:
      - 'Device/**'
      - 'include/**'
      - 'ldscripts/**'

jobs:
  build:
    if: github.repository == 'matismart/release'
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
        fetch-depth: 1

    - name: Checkout private
      uses: actions/checkout@v2
      with:
        repository: matismart/handle
        token: ${{ secrets.MATISMART }}
        path: src

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi cmake

    - name: Build
      working-directory: src
      run: |
        mkdir build && cd build
        cmake -DDEV_TYPE=MT84 .. && make
        mkdir -p ./output && cp *.elf  *.bin "$_"

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: matismart_build
        path: src/build/output/
