name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'matismart/release'
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
        fetch-depth: 1

    - name: Checkout link
      uses: actions/checkout@v2
      with:
        repository: matismart/ldscripts
        token: ${{ secrets.MATISMART }}
        path: ldscripts

    - name: Checkout private
      uses: actions/checkout@v2
      with:
        repository: matismart/handler
        token: ${{ secrets.MATISMART }}
        path: src

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi cmake

    - name: Build
      if: success()
      working-directory: src
      run: |
        sudo chmod +x ./build.sh
        sudo bash ./build.sh

