name: release

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'matismart/release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Checkout ld
        uses: actions/checkout@v2
        with:
          repository: matismart/ldscripts
          token: ${{ secrets.MATISMART }}
          path: ldscripts

      - name: Checkout src
        uses: actions/checkout@v2
        with:
          repository: matismart/handler
          token: ${{ secrets.MATISMART }}
          path: src

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi cmake

      - name: Build
        working-directory: src
        run: |
          sudo chmod +x ./build.sh
          sudo bash ./build.sh

      - name: Get version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Generate tag
        id: tag
        if: startsWith(github.ref, 'refs/tags/') && steps.build.outputs.status == 'success' && !cancelled()
        run: |
          echo "::set-output name=release_tag::Release_${GITHUB_REF/refs\/tags\//}_$(date +"%Y.%m.%d")"
          echo "::set-output name=status::success"

      - name: Package
        id: file
        working-directory: src
        run: |
          echo "# matismart firmware release : " >> CHANGELOG.txt
          echo ${{ github.ref }} >> CHANGELOG.txt
          echo ${{ github.sha }} >> CHANGELOG.txt
          zip -r ${{ steps.get_version.outputs.VERSION }}.zip build CHANGELOG.txt
          zip -r docs.zip scripts

      - name: Release
        uses: stopstopstop/release-action@master
        if: steps.tag.outputs.status == 'success' && !cancelled()
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            src/CHANGELOG.txt
            src/docs.zip
        env:
          GITHUB_TOKEN: ${{ secrets.MATISMART }}

      - name: Send mail
        uses: stopstopstop/mail-action@master
        with:
          server_address:  ${{secrets.MAIL_SERVER}}
          server_port: ${{secrets.MAIL_PORT}}
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: matismart firmware
          body: file://README.md
          to: ${{secrets.MAIL_TO}}
          from: Qitas
          cc: ${{secrets.MAIL_CC}},${{github.event.pusher.email}}
          bcc: ${{secrets.MAIL_BCC}}
          content_type: text/html
          convert_markdown: true
          attachments: src/${{ steps.get_version.outputs.VERSION }}.zip

